apiVersion: v2
name: external-secrets-wrapper
description: Wrapper chart to install external-secrets via Helm
type: application
version: 0.1.0

dependencies:
  - name: external-secrets
    version: "2.2.0"
    repository: https://charts.external-secrets.io
