external-secrets:
  installCRDs: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus

clusterSecretStore:
  enabled: true
  name: aws-ssm
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: aws-credentials
            namespace: external-secrets
            key: secret-key

